const lyrics = [
  "I've had a drink or two and I don't care. There's no fun in what I do if she's not there. I wonder what went wrong, I've waited far too long. I think I'll take a walk and look for her. Though tonight she's made me sad, I still love her. If I find her I'll be glad. I still love her",
  "Spend my days with a woman unkind, smoked my stuff and drank all my wine. Made up my mind, make a new start. Goin' to California with an achin' in my heart. Someone told me there's a girl out there, with love in her eyes and flowers in her hair.",
  "When I was a child, I thought as a child, I spoke as a child. I didn't know better. But now I'm a man. I look like a man. I'm old as a man. And I should now better.",
  "Just a steel-town girl on a Saturday night lookin' for the fight of her life. In the real-time world, no one sees her at all. They all say she's crazy.",
  "This morning I made the call. The one that ends it all. Hanging up I wanted to cry but dammit, this well's gone dry. Not for the money, not for the fame. Not for the power, just no more games. But now I'm safe in the eye of the tornado. I can't replace the lies, that let a 1000 days go.",
  "I hear you knockin' but you can't come in. I know you've been drinkin' gin. You've been cheatin' 'round with other men. I'm busy and you can't come in.",
  "If I'd only had my way. The graveyard would be the place. My man would lay. Nobody knows the way I feel this morning.",
  "Blue moon, you saw me standing alone. Without a dream in my heart. Without a love of my own. Blue moon, you knew just what I was there for. You heard me saying a prayer for someone I really could care for.",
  "And then there suddenly appeared before me, the only one my arms will hold. I heard somebody whisper please adore me. And when I looked, the moon had turned to gold.",
  "I've done some bad things, this I know. If I can't change things, tell me so. It does no good to break your toe on the wall.",
  "Creme tangerine and montelimar. A ginger sling with a pineapple heart. A coffee dessert, yes, you know it's good news. But you'll have to have them all pulled out after the Savoy truffle.",
  "Cool cherry cream and a nice apple tart. I feel your taste all the time we're apart. Coconut fudge really blows down those blues. But you'll have to have them all pulled out after the Savoy truffle.",
  "When I hold you in my arms, and I feel my finger on your trigger, I know nobody can do me no harm.",
  "I've stopped my rambling. I don't do too much gambling these days. These days, these days I seem to think about how all the changes came about my ways. And I wonder if I'd see another highway.",
  "If that's the way you feel, don't change your mind. Be sure this time, I don't really mind. If that's the way you feel, let this be gone. Decide on what you really want.",
  "Look in my eyes and tell me you love me. Tell me you want me. Or, darling, I'll be gone. Look in my eyes and tell me that you're the one for me and that our love will always be, or darling, I'll be gone.",
  "I left my home in Georgia. Headed for the 'Frisco bay. 'Cause I've had nothing to live for and look like nothin's gonna come my way. So I'm just gon' sit on the dock of the bay. Watchin' the tide roll away. I'm sittin' on the dock of the bay, wastin' time.",
  "Now I got those rappers all breakin' up a sweat 'cause everytime I get up on the mic I come correct. And I learned it from the best. Always dressed in something fresh.",
  "Some things come and go. And others stay too long. Hold to what you have. Don't let it slip away through the cracks.",
  "She saw poverty breaking up her home. Wounded warriors took her song away. But the day will come. Jenny Wren will sing when this broken world mends its foolish ways.",
  "Together we can dance forever. Your arms are where I long to be. Especially for two latin lovers. For two latin lovers like you and me.",
  "A thousand true loves will live and die. But a dream lives on forever. The days and the years will go streaking by. But the time has stopped in my dream.",
  "The deeper you go, the higher you fly. The higher you fly, the deeper you go so come on, come on. Come on is such a joy. Come on, let's make it easy. Come on, let's take it easy.",
  "Love, let me sleep tonight on your couch. And remember the smell of fabric of your simple city dress. Oh, that was so real.",
  "Oh, lullaby of birdland. That's what I always hear when you sigh. Never in my woodland could there be ways to reveal in a phrase how I feel. Have you ever heard two turtle doves bill and coo when they love? That's the kind of magic music we make with our lips, when we kiss.",
  "Hey Jude, don't make it bad. Take a sad song and make it better. Remember to let her into your heart. Then you can start to make it better.",
  "I ain't happy, I'm feeling glad. I got sunshine in a bag. I'm useless but not for long, the future is coming on.",
  "I can feel, I can tell. I can feel, I can tell, I can see something is changing. To me change is no stranger. I don't run, I don't hide. I don't run, I don't hide, I don't fight what fate arranges. I don't think about danger. If it was meant for me I'd know just where to go. But if I can take it slow then I might be in control.",
  "In the back of my head. In the back of my head there is doubt, there is suspicion with my new fascination. I don't know what it is. I don't know what it is, you might say it's intuition. It's a true indication.",
  "I don't have plans and schemes. And I don't have hopes and dreams. I don't have anything since I don't have you.",
  "Words are flowing out like endless rain into a paper cup. They slither wildly as they slip away across the universe. Pools of sorrow, waves of joy are drifting through my opened mind, possessing and caressing me.",
  "All my little plans and schemes, lost like some forgotten dreams. Seems like all I really was doing was waiting for you.",
  "She pushed her feet across the boardwalk. She keeps the sunset right with movement in her eyes. She knows she gets away with murder. Swallows up your heart of gold, and I won't know just where we've got to go.",
  "Do what you want to do, and go where you're going to. Think for yourself 'cause I won't be there with you.",
  "I've got a word or two to say about the things that you do. You're telling all those lies, about the good things that we can have if we close our eyes.",
  "I am the world that hides the universal secret of all time. Descruction of the empty spaces is my one and only crime. I've lived a thousand times, I found out what it means to be believed. The thoughts and images, the unborn child that never was conceived.",
  "Living is easy with eyes closed. Misunderstanding all you see. It's getting hard to be someone but it all works out. It doesn't matter much to me.",
  "No one I think is in my tree. I mean it must be high or low. That is, you can't, you know, tune in but it's all right. That is, I think it's not too bad.",
  "I saw her sitting in the rain. Raindrops falling on her. She didn't seem to care. She sat there and smiled at me. Then I knew she could make me happy. Flowers in her hair. Flowers everywhere.",
  "Everybody's talking up a storm. Act like they don't noticed it but here it is and here it comes.",
  "What'll you do when you get lonely and nobody's waiting by your side. You've been running and hiding much too long. You know it's just your foolish pride.",
  "Traveling in a fried out Kombi on a hippie trail, head full of zombie. I met a strange lady, she made me nervous. She took me in and gave me breakfast.",
  "What can I do, what can I be? When I'm with you, I want to stay there. If I'm true, I'll never leave and if I do, I know the way there.",
  "You've got a question, ask it right. Do all I can to hold it in the light. What's there to show when you get out to the coast? This is all I've ever known. It's all I've ever known.",
  "I'm waiting in my cold cell when the bell begins to chime. Reflecting on my past life and it doesn't have much time. 'Cause at five o'clock they take me to the Gallows pole.",
  "Here, making each day of the year. Changing my life with a wave of her hand. Nobody can deny that there's something there. There, running my hands through her hair. Both of us thinking how good it can be. Someone is speaking but she doesn't know he's there.",
  "I want her everywhere and if she's beside me, I know I need never care. But to love her is to need her everywhere. Knowing that love is to share. Each one believing that love never dies. Watching her eyes and hoping I'm always there.",
  "If the stars don't shine, if the moon won't rise, if I never see the setting sun again, you won't hear me cry, this I testify. Please believe me, boy, you know I wouldn't lie, as long as there is you and me, you and me. Nobody, baby, but you and me.",
  "Like a shooting star you appeared before me. Where have you been all my life? All at once I found someone to adore me. Where have you been all my life? Until the moment we met I had no one to cling to. To be just everything to, to be my own true love.",
  "Sometimes life, it takes you by the hair, pulls you down before you know it. It's gone and you're dead again. I've been in places and I won't pretend that I'd make it out just to fall on my head.",
  "This sound is giving for the postman. Another one that's feeling under aurora skies. The summer sleeps in time for autumn. Sticking down your leaves on grass, and I don't know just where we've got to go.",
  "Politicians hide themselves away, they only started the war. Why should they go out to fight? They leave that all to the poor, yeah. Time will tell on their power minds. Making war just for fun. Treating people just like pawns in chess. Wait till their judgement day comes, yeah.",
  "Living for you is easy living. It's easy to live when you're in love and I'm so in love. There's nothing in life but you. I never regret the years I'm giving. They're easy to give when you're in love. I'm happy to do whatever I do for you.",
  "Too many people going underground. Too many reaching for a piece of cake. Too many people pulled and pushed around. Too many waiting for that lucky break. That was your first mistake. You took your lucky break and broke it in two. Now what can be done for you?",
  "Every day she takes a morning bath, she wets her hair. Wraps a towel around her as she's heading for the bedroom chair. It's just another day. Slipping into stockings. Stepping into shoes. Dipping in the pocket of her raincoat. It's just another day.",
  "I come home in the morning light. My mother says, when you gonna live your life right? Oh Mama dear, we're not the fortunate ones. And girls, they wanna have fun. Oh, girls just wanna have fun.",
  "Talking away. I don't know what I'm to say, I'll say it anyway. Today is another day to find you. Shying away. I'll be coming for your love, okay?",
  "Out on the streets for a living. Picture's only begun. Your day is sorrow and madness. Got you under their thumb.",
  "On a dark desert highway, cool wind in my hair. Warm smell of colitas rising up through the air. Up ahead in the distance I saw a shimmering light. My head grew heavy and my sight grew dim. I had to stop for the night.",
  `There she stood in the doorway. I heard the mission bell. And I was thinking to myself "This could be heaven or this could be hell." Then she lit up the candle and she showed me the way. There were voices down the corridor, I thought I heard them say, "Welcome to the Hotel California."`,
  "Sometimes I don't know what to feel. Everything I thought that I knew starts to look so unreal. There's a ringing in my head that keeps me awake at night. Sometimes I don't know what is right. Today I saw a car crush my little dog under its wheel. It did not even stop, it just sped off and out of sight.",
  "I believe if I was all alone I would be better off in a world, my own. I'd forget I ever knew of you and this dream every night that you put me through.",
  "We are close, we are friends. And our love never ends. But in the cold morning light I see that you won't be back for me.",
  "One more day. They said we'd be home for Christmas but I'm still here today. One more day. I went to see the first lieutenant, he said shut up and wait.",
  "I read the news today, oh boy, about a lucky man who made the grade. And though the news was rather sad, well, I just had to laugh. I saw the photograph. He blew his mind out in a car. He didn't notice that the lights had changed. A crowd of people stood and stared. They'd seen his face before. Nobody was really sure if he was from the House of Lords.",
  "Woke up, fell out of bed. Dragged a comb across my head. Found my way downstairs and drank a cup and looking up I noticed I was late. Found my coat and grabbed my hat. Made the bus in seconds flat. Found my way upstairs and had a smoke and somebody spoke and I went into a dream.",
  "When the sun go down, it's the magic hour, the magic hour. And outta all the colors that'll fill up the skies you got green on your mind, I can see it in your eyes.",
  "I hit the Jamaican spot, at the bar, take a seat. I ordered the jerk, she said you are what you eat. You see, I always loved that sense of humor. But tonight, you should have seen how quiet the room was.",
  "I fantasized 'bout this back in Chicago. Mercy, mercy me, that Murcielago. That's me the first year that I blow. How you say broke in spanish? Mi no hablo.",
  "Been traveling these wide roads for so long. My heart's been far from you. Ten thousand miles gone. Oh, I wanna come near and give every part of me. But there's blood on my hands and my lips are unclean.",
  "Yesterday all my troubles seemed so far away. Now it looks as though they're here to stay. Oh, I believe in yesterday. Suddenly, I'm not half the man I used to be. There's a shadow hanging over me. Oh, yesterday came suddenly.",
];